### ISSUE TITLE
unit tests fail when adding angulartics

### ISSUE THREAD

**Issue by bettysteger** [angulartics/angulartics#181]
I use karma for unit tests and I added angulartics.. I changed **nothing** on my tests.. I load this files in karma.conf.js:

```
  'public/assets/components/angular/*.min.js',
  'public/assets/components/angular-translate/angular-translate.min.js', // load in right order
  'public/assets/components/angular-*/*.min.js',
  'public/assets/components/angulartics/src/angulartics.js',
  'public/assets/components/angulartics/src/angulartics-ga.js',
  'public/assets/javascripts/app/app.js',
```

And the strange thing is, that I don't get a specific error just 1 test FAILED with this message:

`Some of your tests did a full page reload!`

When I comment out the failing test, another one fails saying the same error message.. I have no clue what is happening there.. I use `spyOn($location, 'path');` in some of my tests, has that something to do with it?

**Comment by andkuha** [comment]
I still have the problem
Using angular 1.3.8, angular mocks 1.3.8
angulartics 0.17.2

Get error:
Chrome 39.0.2171 (Windows 7) Test test alert details FAILED
        Error: Unexpected request: GET views/pages/signin.html
        No more request expected
            at $httpBackend (C:/Mcafee/workspace/sng/sng-web/bower_components/angular-mocks/angular-mocks.js:1226:9)
            at sendReq (C:/Mcafee/workspace/sng/sng-web/bower_components/angular/angular.js:9615:9)
            at serverRequest (C:/Mcafee/workspace/sng/sng-web/bower_components/angular/angular.js:9331:16)
            at processQueue (C:/Mcafee/workspace/sng/sng-web/bower_components/angular/angular.js:13170:27)
            at C:/Mcafee/workspace/sng/sng-web/bower_components/angular/angular.js:13186:27
            at Scope.$eval (C:/Mcafee/workspace/sng/sng-web/bower_components/angular/angular.js:14383:28)
            at Scope.$digest (C:/Mcafee/workspace/sng/sng-web/bower_components/angular/angular.js:14199:31)
            at Function.$httpBackend.flush (C:/Mcafee/workspace/sng/sng-web/bower_components/angular-mocks/angular-mocks
.js:1525:38)
            at Object.<anonymous> (C:/Mcafee/workspace/sng/sng-web/test/spec/alertsDetailsTest.js:30:19)


describe('Test', function(){
	var scope,localizationService,$httpBackend,http,rootScope,$window;//we'll use this scope in our tests
    //mock Application to allow us to inject our own dependencies
	angular.module('angulartics', []);
	angular.module('angulartics.piwik', []);
	beforeEach(angular.mock.module('app'));

Without angulartics works fine(angulartics js  not included in karma)

    //mock the controller for the same reason and include $rootScope and $controller
    beforeEach(angular.mock.inject(function($rootScope, $controller,localize,_$httpBackend_,$http,_$window_){
    	scope = $rootScope.$new();
    	$httpBackend = _$httpBackend_;
    	http = $http;
    	$window = _$window_;
    	rootScope = $rootScope;
    }));
    it('my test', function(){
    	$httpBackend.when('POST', "/api/test").respond({blah:blah});
    	$httpBackend.flush();
	});
});

**Comment by lpsBetty** [comment]
@andkuha this is not an angulartics error?

you need to allow request for your templates: (I had to added this after adding angular-ui-router)

      $httpBackend.whenGET(/views/).respond(200, '');

**Comment by andkuha** [comment]
Thanks it solved the issue.

**Comment by ryanoncode** [comment]
@adlenafane how did you managed to inject the $analyticsProvider? I'm trying to put it in one of the unit tests of my controllers (in Jasmine) as I seem to be getting some Unexpected requests:  GET. Here's a snippet of my code (in coffeescript):

describe 'Modal Controller: DRPElectionDialogController', ($analyticsProvider) ->
	$analyticsProvider.firstPageview(false);
	beforeEach module 'isfFrontend'

**Comment by adlenafane** [comment]
@ryanoncode I injected it direclty in my application code and not in my unit tests.

**Comment by ryanoncode** [comment]
@adlenafane I tried injecting $analyticsProvider into the controller itself then calling $analyticsProvider.firstPageview(false) in the controller, however it still get bunch of errors like this:

```
Chrome 39.0.2171 (Windows 7) Modal Controller: DRPElectionDialogController DRP dialog tests confirmElection should succeed if DRPElection update succe
eds FAILED
        Error: Unexpected request: GET /wealth/services/user/analytics
        Expected GET scripts/modules/shares/views/drp-election.html
            at $httpBackend (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular-mocks/angular-mocks.js:11
76:9)
            at sendReq (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:7750:9)
            at serverRequest (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:7484:16)
            at wrappedCallback (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:10725:81)
            at wrappedCallback (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:10725:81)
            at C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:10811:26
            at Scope.$eval (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:11726:28)
            at Scope.$digest (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:11554:31)
            at Scope.$apply (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/app/bower_components/angular/angular.js:11832:24)
            at null.<anonymous> (C:/Users/rcruz3/Desktop/GIT-ISF-Split-out/wealth-member-ui-develop/test/spec/controllers/shares/dialog-controllers/DR
```

**Comment by paucls** [comment]
Thanks, it solved my issue too

/* Angulartics configuration */
app.config(function ($analyticsProvider) {
    // turns off to avoid automatic tracking in unit tests
    $analyticsProvider.firstPageview(false);
});

**Comment by pietropeluso** [comment]
I have a different error message when I run tests with karma, and I get this after adding angulartics to the application and from every controller unit test that use $analytics

```
TypeError: 'undefined' is not an object (evaluating 'stateOrName.name')
	    at findState (C:/Users/Pietro.peluso/Documents/SVN/Split/webapp/dev/vendor/angular-ui-routes/angular-ui-router.js:875)
	    at C:/Users/Pietro.peluso/Documents/SVN/Split/webapp/dev/vendor/angular-ui-routes/angular-ui-router.js:1104
	    at C:/Users/Pietro.peluso/Documents/SVN/Split/webapp/dev/vendor/angulartics/angulartics.js:153
	    at invoke (C:/Users/Pietro.peluso/Documents/SVN/Split/webapp/dev/vendor/angular-1.2.15/angular.js:3805)
	    at C:/Users/Pietro.peluso/Documents/SVN/Split/webapp/dev/vendor/angulartics/angulartics.js:169
	    at invoke (C:/Users/Pietro.peluso/Documents/SVN/Split/webapp/dev/vendor/angular-1.2.15/angular.js:3805)
	    at C:/Users/Pietro.peluso/Documents/SVN/Split/webapp/dev/vendor/angular-1.2.15/angular.js:3651
```

Does anyone else have the same problem?

**Comment by ttbarnes** [comment]
+1, `$analyticsProvider.firstPageview(false);` works perfectly.

I had different errors when running karma that I don't understand. No messages I could see that were specifically related to angulartics, but seems to be injector issues with `$$asyncCallbackProvider`. I'm using ng-html2js preprocessor too.

Anyway this works great - thanks @adlenafane

**Comment by irfanraza** [comment]
+1, $analyticsProvider.firstPageview(false);

Works great, I was getting Error: "Define sp" and this was causing further errors . This happens because we added a script block "var sp =  ..some.. function();"  in index.html for angulartics.splunk and when karma runs unit test this becomes undefined and that was causing whole test to fail. Adding just a sp variable in unit test under describe works great even I don't need turn off firstPageview.

Thanks everyone the discussion this helped a lot.

**Comment by tracyalison11** [comment]
+1 $analyticsProvider.firstPageview(false); works for me as well. Thank you soooo much @adlenafane

**Comment by tracyalison11** [comment]
Did anyone receive strict-di errors in their console after implementing this that lead to this page: https://docs.angularjs.org/error/$injector/strictdi?p0=function($analyticsProvider

Implementing this allowed all the unit tests to run successfully but returns an error and a whit screen instead of the app -_-

**Comment by Chunyu379** [comment]
hey everyone so I tried the $analyticsProvider.firstPageview(false); work around everyone stated here but im still getting a bunch of unexpected requests from random test cases after injecting angulartics. Is there any other way to fix it?
