### ISSUE TITLE
Multiple transition errors

### ISSUE THREAD

**Issue by Wuntenn** [angulartics/angulartics#529]
Is anyone able to help me to understand why I'm getting the following errors?:

- `angulartics.js:379 Error: transition superseded`
  > at $StateProvider.$get (http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:2903:42)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4842:19)
    at http://localhost:3000/lib/angular/angular.js:4636:37
    at getService (http://localhost:3000/lib/angular/angular.js:4783:32)
    at injectionArgs (http://localhost:3000/lib/angular/angular.js:4808:58)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4834:18)
    at http://localhost:3000/lib/angular/angular.js:4645:62
    at forEach (http://localhost:3000/lib/angular/angular.js:357:20)
    at createInjector (http://localhost:3000/lib/angular/angular.js:4645:3)
    at doBootstrap (http://localhost:3000/lib/angular/angular.js:1838:20) Possibly unhandled rejection: {}

- `angulartics.js:379 Error: transition prevented`
  > at $StateProvider.$get (http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:2904:41)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4842:19)
    at http://localhost:3000/lib/angular/angular.js:4636:37
    at getService (http://localhost:3000/lib/angular/angular.js:4783:32)
    at injectionArgs (http://localhost:3000/lib/angular/angular.js:4808:58)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4834:18)
    at http://localhost:3000/lib/angular/angular.js:4645:62
    at forEach (http://localhost:3000/lib/angular/angular.js:357:20)
    at createInjector (http://localhost:3000/lib/angular/angular.js:4645:3)
    at doBootstrap (http://localhost:3000/lib/angular/angular.js:1838:20) Possibly unhandled rejection: {}

- `angulartics.js:379 Error: transition aborted`
  > at $StateProvider.$get (http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:2905:39)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4842:19)
    at http://localhost:3000/lib/angular/angular.js:4636:37
    at getService (http://localhost:3000/lib/angular/angular.js:4783:32)
    at injectionArgs (http://localhost:3000/lib/angular/angular.js:4808:58)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4834:18)
    at http://localhost:3000/lib/angular/angular.js:4645:62
    at forEach (http://localhost:3000/lib/angular/angular.js:357:20)
    at createInjector (http://localhost:3000/lib/angular/angular.js:4645:3)
    at doBootstrap (http://localhost:3000/lib/angular/angular.js:1838:20) Possibly unhandled rejection: {}

- `angulartics.js:379 Error: transition failed`
  > at $StateProvider.$get (http://localhost:3000/lib/angular-ui-router/release/angular-ui-router.js:2906:38)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4842:19)
    at http://localhost:3000/lib/angular/angular.js:4636:37
    at getService (http://localhost:3000/lib/angular/angular.js:4783:32)
    at injectionArgs (http://localhost:3000/lib/angular/angular.js:4808:58)
    at Object.invoke (http://localhost:3000/lib/angular/angular.js:4834:18)
    at http://localhost:3000/lib/angular/angular.js:4645:62
    at forEach (http://localhost:3000/lib/angular/angular.js:357:20)
    at createInjector (http://localhost:3000/lib/angular/angular.js:4645:3)
    at doBootstrap (http://localhost:3000/lib/angular/angular.js:1838:20) Possibly unhandled rejection: {}

- `angulartics.js:379 TypeError: Cannot read property 'nodeName' of undefined`
  >at validateAttributeUsage (http://localhost:3000/lib/angular-material/angular-material.js:3950:30)
    at Object.compile (http://localhost:3000/lib/angular-material/angular-material.js:3832:13)
    at applyDirectivesToNode (http://localhost:3000/lib/angular/angular.js:9444:32)
    at compileNodes (http://localhost:3000/lib/angular/angular.js:8804:15)
    at compileNodes (http://localhost:3000/lib/angular/angular.js:8816:15)
    at http://localhost:3000/lib/angular/angular.js:9951:38
    at processQueue (http://localhost:3000/lib/angular/angular.js:16648:37)
    at http://localhost:3000/lib/angular/angular.js:16692:27
    at Scope.$eval (http://localhost:3000/lib/angular/angular.js:17972:28)
    at Scope.$digest (http://localhost:3000/lib/angular/angular.js:17786:31) 
These **all** occur each time I load the view. I'm only able to see that it's looking for an element which isn't there.

I'm using Angulartics: 1.3.0 and Angulartics-google-analytics 0.4.0

**Comment by timelf123** [comment]
Can't speak to where the error comes from exactly, but I know it is related to ui-router 1.x.

Do you have the same issue if using the non minified source? Could be related to https://github.com/angulartics/angulartics/issues/530

**Comment by Wuntenn** [comment]
Hey thanks @timelf123, Not sure how I managed to resolve it (I say resolve but I actually upgraded to a fresh set of errors). They stopped after a reboot from an Apple update (strange!!).

I'm in no hurry to re-produce that error. Seems like some serious knowledge of the internals are required to suss it.

**Comment by Wuntenn** [comment]
I think I've found the source of my woes. Angulartics seems to have issues with SVG's and duplicate ID's and it's also saying that some controllers aren't registered when I they've been fine and working for months.

Not sure what's changed recently but Angulartics is stopping my stuff from working.

**Comment by amyscoville** [comment]
I ran across this same issue and my problem was that I was loading ui-router AFTER my main module
